#!/bin/bash
#
# Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# This software product is a proprietary product of Nvidia Corporation and its affiliates
# (the "Company") and all right, title, and interest in and to the software
# product, including all associated intellectual property rights, are and
# shall remain exclusively with the Company.
#
# This software product is governed by the End User License Agreement
# provided with the software product.
#

HW_VERSION="/var/run/hw-management/system/config1"
SENSORS_CONF_FILE="/usr/share/sonic/platform/sensors.conf"
SENSORS_CONF_FILE_A1="/usr/share/sonic/platform/sensors.conf.a1"

function get_sensor_conf_path() {
    local _HW_VERSION="0"
    if [[ -e $HW_VERSION ]]; then
        _HW_VERSION=$(cat $HW_VERSION 2>&1)
        if [[ "$_HW_VERSION" == "1" ]]; then
            if [[ -e $SENSORS_CONF_FILE_A1 ]]; then
                echo $SENSORS_CONF_FILE_A1
                return
            fi
        fi
    fi
    echo $SENSORS_CONF_FILE
}

get_sensor_conf_path
